### PR TITLE
chore: fix eyebrow for L3 hero

### LINKED ISSUE #343: L3 Hero should have automatic eyebrow text

### PR DESCRIPTION
**Pull request by mhaack**
L3 pages should get an automatic eyebrow text based on the content type, but only if there is non set.

Fix #343

Test URLs:
- Before: https://main--hlx-test--urfuwo.hlx.live/blog/2023/11/idc-marketscape-sap-a-leader-cloud-enabled-sourcing-applications
- After: https://hero-l3--hlx-test--urfuwo.hlx.live/blog/2023/11/idc-marketscape-sap-a-leader-cloud-enabled-sourcing-applications

### CODE REVIEW

File: aemedge/blocks/hero/hero.js [hunk 1]
```diff
@@ -61,17 +60,27 @@ async function replacePlaceholderText(elem) {
...
+
+  // extract block content
   const hero = document.createElement('udex-hero-banner');
-  const intro = block.querySelector('h6');
   const heading = block.querySelector('h1');
+  const eyebrow = block.querySelector('h6');
+  let eyebrowText = eyebrow?.textContent;
+  if (!eyebrowText && isArticle) { // if no eyebrow text is set, use the content type for articles
+    const placeholderText = placeholder[toCamelCase(`content-type/${getMetadata('content-type')}`)];
+    eyebrowText = placeholderText || getMetadata('content-type');
```
Comment (saurabh-khare) [inline aemedge/blocks/hero/hero.js:74]: `getMetadata('content-type')` must be converted to camel case e.g. **original-research**

File: aemedge/blocks/hero/hero.js [hunk 2]
```diff
@@ -61,17 +60,27 @@ async function replacePlaceholderText(elem) {
  * @param {Element} block The footer block element
  */
 export default async function decorate(block) {
-  const isMediaBlend = block.classList.contains('media-blend') || getMetadata('template') === 'article';
+  const isArticle = getMetadata('template') === 'article';
+  const isMediaBlend = block.classList.contains('media-blend') || isArticle;
```
Comment (saurabh-khare) [inline aemedge/blocks/hero/hero.js:64]: This can be` isArticle || block.classList.contains('media-blend');` to short circuit in first expression.

File: aemedge/blocks/hero/hero.js (hunk 1 above)
Comment (mhaack) [reply aemedge/blocks/hero/hero.js:74]: In this case, if we use it as fallback if no placeholder exists not here the content type value looks better.

File: aemedge/blocks/hero/hero.js (hunk 2 above)
Comment (mhaack) [reply aemedge/blocks/hero/hero.js]: fixed

File: aemedge/blocks/hero/hero.js (hunk 1 above)
Comment (saurabh-khare) [reply aemedge/blocks/hero/hero.js:74]: Yes thats fine. What I was wondering if we want to show the fallback value as **original-research** or **Original Research**?

Comment (mhaack) [reply aemedge/blocks/hero/hero.js:74]: It will be original-research in capital letters. But given we have placeholders for all it should not show that at all.

Comment (saurabh-khare) [reply aemedge/blocks/hero/hero.js:74]: Ok I thought better would be 
`eyebrowText = placeholderText || toCamelCase(getMetadata('content-type'));`

**Review by saurabh-khare — APPROVED** [review]

File: aemedge/blocks/hero/hero.js (hunk 1 above)
Comment (mhaack) [reply aemedge/blocks/hero/hero.js]: Ok, I did some more test locally, I agree, change it.
